### ISSUE TITLE
Service Temporarily Unavailable

### ISSUE THREAD

**Issue by 00Bock** [InnoZ/RubyCars#17]
Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.2.15 (CentOS) Server at www.rubycars.org Port 80

@kjoscha: any clue what could be the reason?

**Comment by kjoscha** [comment]
I just made an investigation and found out, that the unicorn svc service throws an error
`/usr/bin/env: ruby_executable_hooks: No such file or directory`
at any web access. I couldn't fix it so far, but started unicorn in a detached tmux session, so that it is accessible again. Disadvantage is, that the process will be killed at any server restart. I contact the uberspace support and ask for a hint.

**Comment by 00Bock** [comment]
service is back online... any clue what happened?

**Comment by BenSto** [comment]
closed if not reopen please.
